services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movie_db
    volumes:
      - ./mongo_data:/data/db
    networks:
      - nosql_network

  # MongoDB Web UI (Mongo Express)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: express
    depends_on:
      - mongo
    networks:
      - nosql_network

  # Cassandra Service
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"  # CQL Native Port
      - "9160:9160"  # Thrift Port (optional)
    volumes:
      - ./cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "NoSQL Cluster"
      CASSANDRA_PASSWORD: cassandra  # only this works by default
    networks:
      - nosql_network

networks:
  nosql_network:
    driver: bridge
